### ISSUE TITLE
Stopped working for me all of a sudden

### ISSUE THREAD

**Issue by nikivdev** [jvandyke/alfred-hastebin#4]

**Comment by jvandyke** [comment]
Looks like it might have to me too... looking into it. Thanks for the heads up @nikitavoloboev

**Comment by jvandyke** [comment]
Looks like `curl -X POST -s -d "test to be sent" http://hastebin.com/documents` has stopped returning a key 😮  Still investigating.

**Comment by jvandyke** [comment]
@nikitavoloboev The latest release should fix it. Can you install and let me know?

**Comment by nikivdev** [comment]
Downloaded the new workflow from the repo. Nothing happens when I activate it.

**Comment by jvandyke** [comment]
I downloaded, installed and used and I get a hastebin URL for all the haste commands...

What version of Alfred are you using and what's your system version?

You may also want to open the workflow in Alfred's settings and toggle debug mode (![](https://cl.ly/3I3H012X2Q2E/Image%202017-01-06%20at%2010.43.49%20AM.png)) to see if there's an error when you run it.

**Comment by nikivdev** [comment]
I am using the latest version of Alfred : 3.2.1 : 


![2017-01-06 at 16 46](https://cloud.githubusercontent.com/assets/6391776/21723163/b7c1f8c4-d42f-11e6-949d-bbf1ab84022d.png)


And I am on El Captain 10.11.6

I have tried using the debug mode, nothing shows there either. :(

**Comment by jvandyke** [comment]
I'm on Sierra, but I don't see why it wouldn't work. It's just using bash.

Did it properly install the latest version of the workflow? Do you see v1.1.2 at the top?

![](https://cl.ly/300N35423V3F/Image%202017-01-06%20at%2010.48.16%20AM.png)

**Comment by nikivdev** [comment]
I have uninstalled it and installed it again. Now it is working. Thank you. :)

Not sure why it didn't upgrade the first time.

**Comment by jvandyke** [comment]
Strange, but I'm glad you got it working. Hard to debug remotely :)

Thanks for the report and help 🎁
